gemdos.Cconws("Run auto tests: largest free memory block " ..
  gemdos.Malloc(-1) .. "\r\n")

dofile("dcreate.lua")
dofile("ddelete.lua")
dofile("dfree.lua")
dofile("dgetdrv.lua")
dofile("dgetpath.lua")
dofile("dsetdrv.lua")
dofile("dsetpath.lua")
dofile("fattrib.lua")
dofile("fclose.lua")
dofile("fcreate.lua")
dofile("fdatime.lua")
dofile("fdelete.lua")
dofile("fdup.lua")
dofile("fforce.lua")
dofile("fopen.lua")
dofile("fread.lua")
dofile("frename.lua")
dofile("fseek.lua")
dofile("fsfirst.lua")
dofile("fsnext.lua")
dofile("fwrite.lua")
dofile("malloc.lua")
dofile("mfree.lua")
dofile("mshrink.lua")
dofile("pexec0.lua")
dofile("pterm.lua")
dofile("pterm0.lua")
dofile("sversion.lua")
dofile("tgetdate.lua")
dofile("tgettime.lua")
dofile("tsetdate.lua")
dofile("tsettime.lua")
dofile("utility.lua")
